services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: graduation_app_development
    ports:
      - "5433:5432"

  web:
    build: .
    command: bash -c "sleep 10 && rm -f /rails/tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
      - SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

volumes:
  bundle_cache: